apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-api-2
  description: Retrieve test api 2
spec:
  type: openapi
  lifecycle: production
  owner: AdamFamily
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Test API 2
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
