---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: apiV10-system
  description: V10 API Description
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apiV10-website-component
  annotations:
    endoflife.date/products: angular@17,nginx@1.25
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [apiV10]
  consumesApis: 
    - apiV5
    - apiV8
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: apiV10
  description: API V10 Description
spec:
  type: REST
  lifecycle: develop
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
